### ISSUE TITLE
Unity - Template Wallet

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Open-Grants-Program#47]
Template Wallet, integrated over the ServiceLayer and the GameEngine, including functionalities (Creating Wallet (Private Key Ed or Sr), using a Mnemonic seed), Restoring Wallet, Transfering Coins, Balance Update, Error handling)

**Comment by dimitrispaxinos** [comment]
In the [SubstrateNET.UnityDemo](https://github.com/ajuna-network/SubstrateNET.UnityDemo) repo and on branch `substrate-seminar`, we implemented a Unity demo where the following is possible:

- Create Wallet and store in the local file storage
- Restore wallet from file storage
- Transfer Balance from Alice to the newly created wallet account
- Information about the state of the executed extrinsic. 

We can see how this works in this [video]().

**Comment by dimitrispaxinos** [comment]
The respective Wallet Template was submitted today to the asset store for review. The review process takes 4-6 weeks. 
We are attaching screenshots of the submitted asset. 

![image (13)](https://user-images.githubusercontent.com/4278331/205990486-8a2e1f98-3e1e-46cb-af45-38c3ff5272d4.png)
![image (12)](https://user-images.githubusercontent.com/4278331/205990498-b294e4c4-de2a-41a0-a387-d039ae39f047.png)
