### ISSUE TITLE
Unity - Template GameEvent and Matchmaker

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Open-Grants-Program#48]
Template with On chain GameEvent and Pallet Matchmaker, where User can queue up to a match and animations that are executed on on chain game events
--

**Comment by dimitrispaxinos** [comment]
**On-chain Game Events**

Regarding the on-chain game events, we extended the Wallet implementation in the [SubstrateNET.UnityDemo](https://github.com/ajuna-network/SubstrateNET.UnityDemo). 

We play a sound on the balance transfer extrinsic finalization event in this case. 

The code can be found on the [unity-on-chain-game-event](https://github.com/ajuna-network/SubstrateNET.UnityDemo/tree/unity-on-chain-game-event)  branch together with a short [video explanation](https://www.loom.com/share/0274c9fe2d94427c93c38849d0c14cef). 

**Pallet Matchmaker, where the user can queue up for a match and animations**

This was covered in Milestone 2 and issue #41, where the Game Dot4G is played between two bots using the Matchmaker Pallet. 

The issue also links to a [demo video](https://drive.google.com/file/d/1-fj3HUAQsFvYj8Ifh8mJdnfyf8uLy9zm/view) showing a game between a Unity client and a bot. The Unity client responds with animations to the bot opponent's actions.
