### ISSUE TITLE
Unity - Tutorial Video "Implementing a new chain and accessing it with unity"

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/Open-Grants-Program#52]
Tutorial video on implementing a new chain and accessing it with unity

**Comment by dimitrispaxinos** [comment]
We have created the [SubstrateNET.BasicUnityDemo](https://github.com/ajuna-network/SubstrateNET.BasicUnityDemo) repo which contains a working Unity app that connects to the Substrate Node (monthly-2022-11 release) and gets/listens to the Block Number changes. 

If you want to try out the app, you can find the installation instructions in the repo's README file. Please keep in mind that for this issue, you will need to work on the `main` branch. 


Alternatively, you can see how everything works in the following three videos that explain the whole process:

1. [We first generate the necessary .NET projects based on our node using the Ajuna.SDK](https://www.youtube.com/watch?v=27k8vxCrXcY)
2. [We then have to generate the necessary DLLs for our Unity project](https://www.youtube.com/watch?v=c_FpDCys3YI)
3. [Walkthrough of the Unity implementation that uses the above DLLs](https://www.loom.com/share/30ecfaaf0e45427c9b69a9c617711e57).

Videos 1 and 2 describe functionality already covered in previous milestones. Therefore, please feel free to move straight to 3.
